export const up = `
    CREATE TABLE IF NOT EXISTS tree (
        id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
        name VARCHAR(100) NOT NULL,
        root_node INTEGER REFERENCES node(id) ON UPDATE CASCADE ON DELETE SET NULL,
        creator INTEGER REFERENCES employee(id) ON UPDATE CASCADE ON DELETE SET NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );
`;
