version: "3.8"

services: 
    db:
        image: mysql
        volumes: 
            - mysql:/var/lib/mysql
        ports:
            - 3306:3306
        environment: 
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
            MYSQL_DATABASE: "arag"
            MYSQL_USER: "backend"
            MYSQL_PASSWORD: "secret"

volumes: 
    mysql: