version: "3.3"

services:
    db:
        image: mysql:8.0.21
        command: "--innodb_use_native_aio=0"
        ports:
            - 3307:3306
        volumes:
            - ./database/mysql:/var/lib/mysql
            - ./database/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        deploy:
            restart_policy:
                condition: any
    api:
        image: bastiaan225/arag-api
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./:/app
            - ./node_modules:/app/node_modules
        environment:
            PORT: ${PORT}
        deploy:
            restart_policy:
                condition: any
        depends_on:
            - db
